// This file is automatically generated. Do not edit it directly.
// Types are generated from the Supabase database schema using the Supabase CLI.
/* eslint-disable @typescript-eslint/no-empty-object-type */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Add your tables here
    }
    Views: {
      // Add your views here
    }
    Functions: {
      // Add your functions here
    }
    Enums: {
      // Add your enums here
    }
    CompositeTypes: {
      // Add your composite types here
    }
  }
}

// Project reference: 6d36c6a6-f8b0-49c4-a0f8-a45b313f3171
// Last updated: 2026-03-28T02:28:17.698219
